// <auto-generated />
namespace Insurance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Insurance_More_attributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Insurance_More_attributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201508280725133_Insurance_More_attributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
