// <auto-generated />
namespace Insurance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Insurance_drop_modifiedDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Insurance_drop_modifiedDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201508281408266_Insurance_drop_modifiedDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
