// <auto-generated />
namespace Insurance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Insurance_add_dates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Insurance_add_dates));
        
        string IMigrationMetadata.Id
        {
            get { return "201508281455256_Insurance_add_dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
